In [1]:
import pandas as pd


In [2]:
data = {'Weight':[2,4,5,3,6,5,7], 'Price':[35,60,20,50,50,55,60]}

In [3]:
df=pd.DataFrame(data)

In [4]:
df

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

In [5]:
output_file='dataset.xlsx'
df.to_excel(output_file, index=False)

In [6]:
df=pd.read_excel('dataset.xlsx')

In [7]:
df.head()

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50

In [8]:
x=df['Weight']
y=df['Price']

In [9]:
import numpy as np

In [10]:
#mean
mean_x=np.mean(x)
mean_y=np.mean(y)

In [11]:
#deviations
dev_x=x-mean_x
dev_y=y-mean_y

1.Slope, m = Σ((x - x̄) * (y - ȳ)) / Σ((x - x̄)^2)
2.Intercept, c = ȳ - m * x̄

In [12]:
#coefficient
coefficient=np.sum(dev_x*dev_y)/ np.sum(dev_x**2)
coefficient

2.620967741935484

In [13]:
#intercept

intercept=mean_y-(coefficient*mean_x)
intercept

35.16129032258065

In [14]:
pred_y = (coefficient * 6) + intercept
pred_y

50.88709677419355

# Model 


In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
reg = LinearRegression()

In [17]:
#training
reg.fit(df[['Weight']] , df[['Price']]) 

LinearRegression()

In [18]:
reg.coef_

array([[2.62096774]])

In [19]:
reg.intercept_

array([35.16129032])

In [20]:
df.head()

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50

In [21]:
m = reg.coef_
c = reg.intercept_
m*6 + c

array([[50.88709677]])

In [22]:
df['predicted_price'] = reg.predict(df[['Weight']])

In [23]:
df

Weight  Price  predicted_price
0       2     35        40.403226
1       4     60        45.645161
2       5     20        48.266129
3       3     50        43.024194
4       6     50        50.887097
5       5     55        48.266129
6       7     60        53.508065

In [24]:
df['residiuls'] = df['Price'] - df['predicted_price']

In [25]:
df

Weight  Price  predicted_price  residiuls
0       2     35        40.403226  -5.403226
1       4     60        45.645161  14.354839
2       5     20        48.266129 -28.266129
3       3     50        43.024194   6.975806
4       6     50        50.887097  -0.887097
5       5     55        48.266129   6.733871
6       7     60        53.508065   6.491935

In [26]:
#mse
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(df['Price'], df['predicted_price'])

In [27]:
mse

167.30990783410135

In [28]:
#mae
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(df['Price'], df['predicted_price'])

In [29]:
mae

9.87327188940092